name: CommandBook
main: com.sk89q.commandbook.CommandBookPlugin
version: __VERSION_MACRO__
commands:
    cmdbook:
        description: CommandBook commands
        usage: /<command> <arguments...>
    say:
        description: Say a message
        usage: /<command> <msg...>
    me:
        description: Say an action message
        usage: /<command> <msg...>
    slap:
        description: Slap a player
        usage: /<command> [-s] [-h|-v] [-d] [target]
    shock:
        description: Shock a player
        usage: /<command> [-s] [-k] [-a] [target]
    barrage:
        description: Send a barrage of arrows
        usage: /<command> [-s] [target]
    thor:
        description: Give Thor's hammer
        usage: /<command> [target]
    unthor:
        description: Revoke Thor's hammer
        usage: /<command> [target]
    rocket:
        description: Rocket a player
        usage: /<command> [-s] [-h] [target]
    item:
        aliases: [item, i]
        description: Create an item
        usage: /<command> [-d] [target] <item[:data]> [amount]
    give:
        description: Give an item
        usage: /<command> [-d] <target> <item[:data]> [amount]
    who:
        aliases: [list, playerlist, online, players]
        description: Get the list of players
        usage: /<command> [filter]
    motd:
        description: Show the message of the day
        usage: /<command>
    rules:
        description: Show the rules
        usage: /<command>
    whois:
        description: Tell information about a user
        usage: /<command> [target]
    setspawn:
        description: Set the spawn location
        usage: /<command> [location]
    spawn:
        description: Teleport to spawn
        usage: /<command>
    spawnmob:
        description: Spawn a mob
        usage: /<command> [-d] [-i] [-r] <mob> [count] [location]
    teleport:
        aliases: tp
        description: Teleport to a location
        usage: /<command> [target] <destination>
    bring:
        aliases: [tphere, summon, s]
        description: Bring a player to you
        usage: /<command> <target>
    put:
        aliases: place
        description: Place a player at the location you are looking at
        usage: /<command> <target>
    time:
        description: Set the time of your current world
        usage: /<command> [world] <time|"current">
    weather:
        description: Change the weather
        usage: /<command> <'stormy'|'sunny'> [duration] [world]
    thunder:
        description: Set the thunder state
        usage: /<command> <'on'|'off'> [duration] [world]
    msg:
        aliases: [message, whisper, pm, tell]
        description: Send a private message to a user
        usage: /<command> <target> <message...>
    reply:
        aliases: r
        description: Reply to the last user
        usage: /<command> <message...>
    whereami:
        aliases: [getpos, pos, where]
        description: Get your current location
        usage: /<command> [target]
    compass:
        description: Get your compass direction
        usage: /<command> [target]
    clear:
        description: Clear your inventory
        usage: /<command> [-a] [target]
    ping:
        description: Get back a dummy reply
        usage: /<command>
    pong:
        description: Get back a dummy reply
        usage: /<command>
    kick:
        description: Kick a player by name
        usage: /<command> <target> [reason...]
    ban:
        description: Ban a player by name
        usage: /<command> <target> [reason...]
    unban:
        description: Unban a player by name
        usage: /<command> <target> [reason...]
    isbanned:
        description: Checks if a player's name is banned
        usage: /<command> <target>
    bans:
        description: Ban save/load commands
        usage: /<command> ...
    mute:
        description: Mute a player
        usage: /<command> <target>
    unmute:
        description: Unute a player
        usage: /<command> <target>
    kit:
        description: Get a kit (or list kits)
        usage: /<command> <kit> [target]
    debug:
        description: Get server information / benchmark Minecraft clock speed
        usage: /<command> ...